# version: 2

# models:
#   - name: stg_customers
#     columns:
#     - name: customer_id
#       tests:
#         - unique
#         - not_null

version: 2
# 不允許空值，不允許重複
models:
  - name: practice
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
# 檢查 status 欄位的值必須在指定的集合裡
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
# 檢查：stg_orders.customer_id 中的每個值，都必須出現在 stg_customers.customer_id 裡。
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id